# User-defined operators


# User-defined contexts
[
"t1",
sub{my $d=&during("p","q"); [&and, [&not, &holds([&not, $d],"q")], [&or, $d, &during([&not, "p"],"q")]]}->(),
"t2",
sub{my $d=&during("p","q"); [&or, $d, &during([&not, $d],"q")]}->(),
"t3",
sub{my $d=&during("p","q"); [&and, $d, &during([&not, $d],"q")]}->(),
"t4",
[&le(1), "p"],
"t5",
[&le(2), "p"],
"t6",
[&le(1), [&not, "p"]],
"t7",
[&le(2), [&or, &during("p","q"), &during([&not, "p"],"q")]],
"t8",
[&geRT(1), "p"],
"t9",
[&geRT(2), [&or, &during("p","q"), &during([&not, "p"],"q")]],
"t10",
[&geRT(4), "q"],
"t11",
[&wave(1,0,0,0)],
"t12",
[&wave(1,0,0,0)],
"t13",
[&not, [&wave(1,0,0,0)]],
"t14",
[&and, [&wave(1,2,0,10)], [&wave(2,3,0,10)]],
"t15",
[&delay(1),"p"],
"t16",
[&delay(1),"q"],
"t17",
[&delay(1),[&wave(2,3,0,10)]],
"t18",
&during("p",[&delay(1),[&wave(2,4,10,25)]]),
"t19",
&during([&not, "q"],[&not, "p"]),
"t20",
&occ("p","q"),
"t21",
&occ("q","p"),
"t22",
&occ([&not, "p"],"q"),
"t23",
&occ([&not, "q"],"p"),
"t24",
&occ([&not, "p"],"p"),
"t25",
&btwin("p","q"),
"t26",
&btwin("q","p"),
"t27",
&btwin("p","p"),
"t28",
&between("p","q"),
"t29",
&between("q","p"),
"t30",
&between([&not, "q"],"p"),
"t31",
&between([&not, "p"],"q"),
"t32",
&between([&not, "p"],[&not, "q"]),
"t33",
&between([&not, "q"],[&not, "p"]),
"t34",
&between("p","p"),
"t35",
&between("q","q"),
"t36",
&over("p","q"),
"t37",
&over("q","p"),
"t38",
&over(&holds([&not, &during("p","q")],"q"),"p"),
"t39",
&starts("p","q"),
"t40",
&starts("p","p"),
"t41",
&starts("p",&occ("p","q")),
"t42",
&starts("q",&occ("q",[&not, "p"])),
"t43",
&starts("q",&occ("q","p")),
"t45",
&starts("p",[&or, "p", "q"]),
"t46",
&starts("q",[&or, "p", "q"]),
"t47",
sub{my $d=&during("p","q"); &starts("p",[&and, [&not, &holds([&not, $d],"q")], [&or, $d, &during([&not, "p"],"q")]])}->(),
"t48",
&eq("p","q"),
"t49",
&eq("p","p"),
"t50",
&eq("p",[&not, "p"]),
"t51",
&eq("p",&during("p","q")),
"t52",
&eq(&during("p","q"),&during("p","q")),
"t53",
&eq([&not, &during("p","q")],&during([&not, "p"],"q")),
"t54",
&ends("p",[&or, "p", "q"]),
"t55",
&ends([&not, "p"],[&or, [&not, "p"], [&not, "q"]]),
"t56",
sub{my $d=&during("p","q"); &ends("p",[&and, [&not, &holds([&not, $d],"q")], [&or, $d, &during([&not, "p"],"q")]])}->(),
"t57",
&met("p",[&not, "p"]),
"t58",
&met([&not, "p"],"p"),
"t59",
&met("p",&during([&not, "p"],"q")),
"t60",
&met("p",&between("q","p")),
"t61",
&met("q",&between("p","q")),
"t62",
&met("p",&between([&not, "q"],"p")),
"t63",
&met([&not, "p"],&between([&not, "q"],[&not, "p"])),
"t64",
[&and, "q", [&not, &holds([&not, "p"],"q")]],
"t65",
[&and, "q", [&not, &holds("p","q")]],
"t66",
[&and, [&not, "q"], [&not, &holds("p",[&not, "q"])]],
"t67",
&occ(&starts("p","q"),"q"),
"t68",
&occ(&starts("p","p"),"p"),
"t69",
&occ(&starts("p",&occ("p","q")),&occ("p","q")),
"t70",
&occ(&starts("q",&occ("q",[&not, "p"])),&occ("q",[&not, "p"])),
"t71",
&occ(&starts([&and, "p", "q"],"p"),"p"),
"t72",
&occ(&starts([&and, "p", "q"],"q"),"q"),
"t73",
[&and, "p", [&not, &holds([&not, &during("q","p")],"p")]],
"t74",
[&and, "q", [&not, &holds([&not, &during("p","q")],"q")]],
"t75",
&occ(&over("q","p"),"p"),
"t76",
&occ(&over("p","q"),"q"),
"t77",
[&and, "p", [&not, &holds([&not, &over("p","q")],"p")]],
"t78",
[&and, "q", [&not, &holds([&not, &over("q","p")],"q")]],
"t79",
&met("p",&between("q","p")),
"t80",
&met("q",&between("p","q")),
"t81",
&meets("p",[&not, "p"]),
"t82",
&meets("q",[&not, "q"]),
"t83",
&meets("p",&between("p","q")),
"t84",
&meets("q",&between("q","p")),
"t85",
&occ([&geRT(1), [&not, "p"]],[&not, [&geRT(1), "q"]]),
"t86",
&occ([&geRT(1), "p"],[&not, [&geRT(1), "q"]]),
"t87",
&occ([&geRT(1), "p"],[&not, [&geRT(1), [&not, "q"]]]),
"t88",
[&gt(1), "p"],
"t89",
[&gtRT(1), "p"],
"t90",
[&lt(1), "p"],
"t91",
[&lt(2), "p"],
"t92",
[&ge(1), "p"],
"t93",
[&ge(2), "p"],
"t94",
[&gt(4), "q"],
"t95",
[&ge(4), "q"],
"t96",
&contains("p","q"),
"t97",
&contains("q","p"),
"t100",
&contains("p","p"),
"t101",
&contains("q",[&not, "q"]),
"t102",
&contains("q",[&and, "p", "q"]),
"t103",
&ended("p","q"),
"t104",
&ended("q","p"),
"t106",
&ended("q",[&and, "p", "q"]),
"t107",
&overlaps("p","q"),
"t108",
&overlaps("q","p"),
"t110",
&overlaps([&not, "q"],"p"),
"t111",
&overlaps("q","q"),
"t112",
&overlaps("q",[&and, "q", "p"]),
"t113",
&overlaps("q",[&or, "q", "p"]),
"t114",
&overlapped("p","q"),
"t115",
&overlapped("q","p"),
"t116",
&overlapped("q",[&and, "p", "q"]),
"t117",
&overlapped("q",[&or, "p", "q"]),
"t118",
&started("p","q"),
"t119",
&started("q","p"),
"t120",
&started("q",[&and, "p", "q"]),
"t121",
&before("p","q"),
"t122",
&before("q","p"),
"t123",
&before("p",[&not, "q"]),
"t124",
&before("q",[&and, "p", [&not, "q"]]),
"t125",
&after("p","q"),
"t126",
&after("q","p"),
"t127",
&after("p",[&not, "q"]),
"t128",
&after("q",[&not, "p"]),
"t129",
&btw("p","q"),
"t130",
&btw("q","p"),
"t131",
&btw("p",[&not, "q"]),
"t132",
[&true],
"t133",
[&false],
"t134",
[&and, [&true], [&false]],
"t135",
[&and, [&true], [&true]],
"t136",
[&or, [&true], [&false]],
"t137",
[&or, [&false], [&false]],
"t138",
&occ("p",[&true]),
"t139",
&during("p",[&true]),
"t140",
&contains([&true],"p"),
"t141",
[&gtRT(2), "p"],
"t142",
[&gtRT(3), "p"],
"t143",
[&gtRT(1), [&not, "p"]],
"t144",
[&gtRT(2), [&not, "p"]],
"t145",
[&gtRT(10), [&not, "p"]],
]
